---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sklearn-rf
  name: sklearn-rf
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: sklearn-rf
    spec:
      containers:
      - args:
        - --port=9000
        - --model_name=sklearn-rf
        - --model_base_path=gs://pengyu-ml-test/sklearn-rf
        command:
        - /usr/bin/tensorflow_model_server
        image: gcr.io/kubeflow/model-server:1.0
        imagePullPolicy: IfNotPresent
        name: sklearn-rf
        ports:
        - containerPort: 9000
      - command:
        - python
        - /usr/src/app/server.py
        - --port=8000
        - --rpc_port=9000
        - --rpc_timeout=10.0
        image: gcr.io/shopify-codelab-and-demos/http-proxy:1.6
        imagePullPolicy: IfNotPresent
        name: sklearn-rf-http-proxy
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sklearn-rf
  name: sklearn-rf
  namespace: default
spec:
  ports:
  - name: tf-serving
    port: 9000
    targetPort: 9000
  - name: tf-serving-proxy
    port: 8000
    targetPort: 8000
  selector:
    app: sklearn-rf
  type: LoadBalancer
